---
version: 2
formats: []
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: poetry
      path: .
      command: "poetry install --with docs"

sphinx:
  configuration: docs/conf.py
