name: build-sign-image
on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/publish-sign.yml
  workflow_dispatch:

permissions:
  id-token: write        #  🔑  necesario para OIDC keyless
  packages: write        #  push a GHCR
  contents: read
  security-events: write #  subir SARIF si luego quisieras

env:
  IMAGE_NAME: ghcr.io/genaoking/nornir-demo

jobs:
  build-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---------- Build & push ----------
      - name: Log-in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
            docker build \
            --build-arg PYTHON=3.11 \
            -t $IMAGE_NAME:${{ steps.vars.outputs.sha_short }} .


      - name: Push image
        run: docker push $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}

      # ---------- Install Cosign ----------
      - name: Install Cosign CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/sigstore/cosign/main/install.sh | sudo sh -s -- -b /usr/local/bin v2.2.4

      # ---------- Sign (keyless) ----------
      - name: Sign image with Cosign keyless
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes --keyless $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}

      # ---------- Verify (optional) ----------
      - name: Verify signature
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify --keyless $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}

      # ---------- Generate SBOM ----------
      - name: Generate SBOM (Syft)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.93.0
          syft $IMAGE_NAME:${{ steps.vars.outputs.sha_short }} -o spdx-json=sbom.spdx.json

      - uses: actions/upload-artifact@v4
        with:
          name: image-signature-and-sbom
          path: |
            *.sig
            sbom.spdx.json
