name: security-trufflehog
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog v3
        uses: trufflesecurity/trufflehog@v3.77.0
        with:
          path: .
          json: true
          sarif: trufflehog.sarif
          extra_args: --only-verified

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trufflehog.sarif
