name: security-trufflehog
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:                       # necesarios para code-scanning
  contents: read
  security-events: write

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # escanea TODO el historial

      # La acción escanea y sube los hallazgos en SARIF
      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog-actions-scan@v0.13.0
        with:
          scan: git
          path: .
          extra_args: --only-verified   # opcional, ignora falsos positivos
