# .github/workflows/security-trufflehog.yml
name: security-trufflehog
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # para subir SARIF

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      # analiza TODO el historial

      - name: TruffleHog OSS scan
        uses: trufflesecurity/trufflehog@v3
        with:
          scan: git           # modo histórico completo
          extra_args: --only-verified   # opcional, filtra falsos positivos
          upload-sarif: true  # default=true → sube a Code Scanning
          sarif_file: trufflehog.sarif  # nombre del artefacto
          fail: false         # no marcar el job rojo por hallazgos
