name: security-trufflehog
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read          # leer el repo
  security-events: write  # subir SARIF a Code-Scanning

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      # escanea TODO el historial git

      - name: TruffleHog OSS scan
        uses: trufflesecurity/trufflehog@v3.90.3   # <-- tag existente
        with:
          scan: git                 # modo histórico completo
          upload-sarif: true        # la acción genera y sube trufflehog.sarif
          extra_args: --only-verified   # opcional: evita falsos positivos
          fail: false               # no marcar el job rojo por hallazgos
