name: security-semgrep
on:
  push:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep OSS ruleset
        run: |
          # Genera SARIF directamente
          semgrep scan \
                 --config p/ci \
                 --sarif --output semgrep.sarif \
                 src \
                 || true     # findings ≠ fallo de pipeline

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
